name: smartmedia_campaign_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.5.1
  url_launcher: ^6.1.10
  provider: ^6.1.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.5
  fl_chart: ^0.66.0
  animate_do: ^3.3.7
  intl: ^0.18.1
  carousel_slider: ^5.0.0
  file_picker: ^10.1.7
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.2.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  flutterfire_cli: ^0.1.1+2
  get_it: ^8.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
