// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9rBly6visG5Zrtl0VBE7YmoKNXhbtUDI',
    appId: '1:771380337178:web:97c50d7526f9e80bbc4fa3',
    messagingSenderId: '771380337178',
    projectId: 'smartmedia-d9750',
    authDomain: 'smartmedia-d9750.firebaseapp.com',
    storageBucket: 'smartmedia-d9750.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkmh-mNCK_-jk3Ymm4d3nK53xPNUPE8o',
    appId: '1:771380337178:android:1d8b04a66a71d1b5bc4fa3',
    messagingSenderId: '771380337178',
    projectId: 'smartmedia-d9750',
    storageBucket: 'smartmedia-d9750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5kn_X-XEBSPyJ3Mg6lHGSp270igaAM9I',
    appId: '1:771380337178:ios:2e0488d8965875efbc4fa3',
    messagingSenderId: '771380337178',
    projectId: 'smartmedia-d9750',
    storageBucket: 'smartmedia-d9750.firebasestorage.app',
    iosBundleId: 'com.example.smartmediaCampaignManager',
  );
}
