name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Get dependencies
        run: flutter pub get
      
      # Add this step to fix the base href in index.html
      - name: Fix index.html base href
        run: |
          if ! grep -q '<base href="\$FLUTTER_BASE_HREF">' web/index.html; then
            sed -i 's/<head>/<head>\n  <base href="$FLUTTER_BASE_HREF">/' web/index.html
          fi
      
      # Modify build command to specify web-renderer
      - name: Build web
        run: flutter build web --release --base-href /smartmedia_campaign_manager/ --web-renderer html
      
      - name: Create .nojekyll file
        run: touch build/web/.nojekyll
      
      - name: Create test file
        run: |
          cat > build/web/test.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Test Page</title>
          </head>
          <body>
            <h1>Test Page Works!</h1>
            <p>If you can see this, your GitHub Pages deployment is working.</p>
          </body>
          </html>
          EOL
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web