name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Update base href in index.html
        run: |
          sed -i 's|<base href="\$FLUTTER_BASE_HREF">|<base href="/smartmedia_campaign_manager/">|' web/index.html

      - name: Build Flutter web
        run: flutter build web --release --base-href /smartmedia_campaign_manager/ --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/

      - name: Create .nojekyll
        run: touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
