name: Flutter Web Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' 
        channel: stable

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Web App
      run: flutter build web
